### ISSUE TITLE
[WEB, ANDROID]onMessagingChannelUpdateReceived event is too slow or not working

### ISSUE THREAD

**Issue by hanung** [smilefam/sendbird-sample#9]
![2016-02-04 7 53 29](https://cloud.githubusercontent.com/assets/2052265/12813364/e09ee202-cb7a-11e5-83af-2346b37dae16.png)

onMessagingChannelUpdateReceived event is too slow or not working

Check please.

**Comment by sf-harry-kim** [comment]
Due to the internal issue firing onMessagingChannelUpdateReceived events has been delayed a couple of hours. We fixed the issue and It should work now. Thank you for informing us about the issue.
If you have further inquiry please contact us with support@sendbird.com.
